name: Release

on:
  release:
    types: [ published ]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  package:
    name: Package
    uses: ./.github/workflows/package.yml

  release:
    name: Release
    environment: release
    needs: [ test, package ]
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.whl

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
